image: node:latest

before_script:
    - apt-get update -yq
    - npm install

staging:
    type: deploy
    script:
        - apt-get update -yq
        - apt-get install -yqq ruby ruby-dev
        - gem install dpl
        - dpl --provider=heroku --api-key=`heroku auth:token`
    only:
    - master